version: "3.9"

services:
  user-service:
    build:
      context: src/user-service
      target: user-service
    environment:
      ENV: local
    expose:
      - 80
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    ports:
      - 80:80
    volumes:
      - ./src/user-service:/home/node/app
